#! /bin/sh
pgrep -x sxhkd > /dev/null || sxhkd &
# $HOME/.config/polybar/launch.sh

xset -dpms s off
bash ~/.config/polybar/docky/launch.sh

# MAIN_MONITOR=$(xrandr | grep primary | awk '{print $1}')
MAIN_MONITOR=$(xrandr | grep -w connected | grep -v primary | awk '{print $1}')

#bspc monitor {MAIN_MONITOR} -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor -d 1 2 

bspc config border_width         3
bspc config border_radius       10
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

